### ISSUE TITLE
'toLowerCase' of undefined

### ISSUE THREAD

**Issue by HarleySG** [malopez1578/cli-games-webpack#1]
Hola,

Al ejecutar el game --start --port 3030 salio el siguiente error:

https://github.com/malopez1578/cli-games-webpack/blob/7f85df9986526abf913db3c7a85086f413398b4d/src/cli.js#L81

Este hace referencia a que una variable "answers" llena undefined

**Comment by malopez1578** [comment]
Se corrige el erro de la línea 81
